#!/usr/bin/env python3
"""
Preview the weather-icon bitmaps and export them to the firmware header.

- (no args): open a window with all icons (day + night) scaled up.
- --png FILE: save the preview grid to a PNG instead of opening a window.
- --export:   (re)generate ../../weather_icons.h for the sketch.

Source icons come from _src/ (run fetch_icons.sh first). Requires Pillow.
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from PIL import Image, ImageDraw

import icons

HERE = os.path.dirname(os.path.abspath(__file__))
HEADER_PATH = os.path.normpath(os.path.join(HERE, "..", "..", "weather_icons.h"))
SCALE = 5
PAD = 12
COLS = 5


def _tiles():
    # (label, name, night) for every icon we render
    tiles = [(n, n, False) for n in icons.ICONS]
    tiles += [(n + " (night)", n, True) for n in icons.ICONS if icons.has_night(n)]
    return tiles


def montage():
    tiles = _tiles()
    rows = (len(tiles) + COLS - 1) // COLS
    cw = icons.ICON_W * SCALE + PAD * 2
    ch = icons.ICON_H * SCALE + PAD * 2 + 14
    sheet = Image.new("L", (cw * COLS, ch * rows), 30)
    sd = ImageDraw.Draw(sheet)
    for idx, (label, name, night) in enumerate(tiles):
        r, c = divmod(idx, COLS)
        ox, oy = c * cw, r * ch
        big = icons.render(name, night).convert("L").resize(
            (icons.ICON_W * SCALE, icons.ICON_H * SCALE), Image.NEAREST)
        sd.rectangle([ox + PAD - 1, oy + PAD - 1,
                      ox + PAD + icons.ICON_W * SCALE, oy + PAD + icons.ICON_H * SCALE],
                     outline=90)
        sheet.paste(big, (ox + PAD, oy + PAD))
        sd.text((ox + PAD, oy + PAD + icons.ICON_H * SCALE + 2), label, fill=200)
    return sheet


def _c_array(name, night):
    img = icons.render(name, night)
    px = img.load()
    w, h = icons.ICON_W, icons.ICON_H
    row_bytes = (w + 7) // 8
    arr = "icon_" + name + ("_night" if night else "")
    lines = [f"static const unsigned char PROGMEM {arr}[] = {{"]
    for y in range(h):
        row = []
        for b in range(row_bytes):
            byte = 0
            for bit in range(8):
                x = b * 8 + bit
                if x < w and px[x, y]:
                    byte |= (0x80 >> bit)
            row.append(byte)
        lines.append("  " + ", ".join(f"0x{b:02X}" for b in row) + ",")
    lines.append("};")
    return "\n".join(lines)


def emit_header():
    out = []
    out.append("#pragma once")
    out.append("// Weather icons for the SSD1306 (1-bit, drawBitmap), with day/night variants.")
    out.append("// Source: Dhole's pixel weather icons (32x32, hand-made for monochrome),")
    out.append("//   https://github.com/Dhole/weather-pixel-icons  (CC BY-SA 4.0).")
    out.append("// Auto-generated by tools/icon_sim/bitmap_sim.py --export -- do not edit by hand.")
    out.append("#include <Arduino.h>")
    out.append("")
    out.append(f"#define WEATHER_ICON_W {icons.ICON_W}")
    out.append(f"#define WEATHER_ICON_H {icons.ICON_H}")
    out.append("")
    for name in icons.ICONS:
        out.append(f"// {name}  ({icons.ICON_FILES[name]})")
        out.append(_c_array(name, False))
        out.append("")
    for name in icons.ICONS:
        if icons.has_night(name):
            out.append(f"// {name} night  ({icons.NIGHT_FILES[name]})")
            out.append(_c_array(name, True))
            out.append("")
    out.append("// Maps a wttr.in WWO condition code (one-line %i) to an icon bitmap,")
    out.append("// picking the night variant when available. Returns nullptr if unknown.")
    out.append("static inline const unsigned char* weatherIconForCode(int code, bool night)")
    out.append("{")
    out.append("  switch (code)")
    out.append("  {")
    for code in sorted(icons.CODE_TO_ICON):
        name = icons.CODE_TO_ICON[code]
        if icons.has_night(name):
            out.append(f"    case {code}: return night ? icon_{name}_night : icon_{name};")
        else:
            out.append(f"    case {code}: return icon_{name};")
    out.append("    default: return nullptr;")
    out.append("  }")
    out.append("}")
    out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--png")
    ap.add_argument("--export", action="store_true")
    args = ap.parse_args()

    if args.export:
        with open(HEADER_PATH, "w", encoding="utf-8") as f:
            f.write(emit_header())
        print("wrote", HEADER_PATH)
        return

    sheet = montage()
    if args.png:
        sheet.save(args.png)
        print("saved", args.png)
        return

    import tkinter as tk
    from PIL import ImageTk
    root = tk.Tk()
    root.title("Weather icon preview (icon_sim)")
    photo = ImageTk.PhotoImage(sheet)
    tk.Label(root, image=photo, bg="black").pack()
    root.mainloop()


if __name__ == "__main__":
    main()
